### USERS
POST http://localhost:8000/api/register
content-type: application/json

{  
  "last_name":"MARTINEZ",  
  "first_name":"Henri",
  "email":"henri.talfumier@wanadoo.fr",
  "role":"editor",
  "pwd":"1234H67£"
}

