@admin_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibGFzdF9uYW1lIjoiTUFSVElORVoiLCJmaXJzdF9uYW1lIjoiSGVucmkiLCJlbWFpbCI6ImhlbnJpLnRhbGZ1bWllckB3YW5hZG9vLmZyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzE3NjA4NDkwLCJleHAiOjE3MTc2NjI0OTB9.eazpDjUG8tny4_8gpJM2kIvnmmC1ti_nBav1T1JwdAc
@user_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibGFzdF9uYW1lIjoiTUFSVElORVoiLCJmaXJzdF9uYW1lIjoiSGVucmkiLCJlbWFpbCI6ImhlbnJpLnRhbGZ1bWllcjFAd2FuYWRvby5mciIsInJvbGUiOiJlZGl0b3IiLCJpYXQiOjE3MTc2MTA2NDIsImV4cCI6MTcxNzY2NDY0Mn0.kdckHjKrAtBDIi57fMk_N9GcrUkI2qayrYLMdtPP1nk

### DATES
GET http://localhost:8000/api/dates

### ARTISTS
GET http://localhost:8000/api/artists
###
GET http://localhost:8000/api/artists/28881
###
PATCH http://localhost:8000/api/artists/28881
content-type: application/json

{
  "name":"Cosmic Jazz Odyssey"
}
###
POST http://localhost:8000/api/artists
content-type: application/json

{
  "name":"xxxx",
  "country":"ccccc",
  "description":"vvvvvv",
  "composition":"vvvv",
  "style":"nnnnnnnnn"
}
###
DELETE  http://localhost:8000/api/artists/28925

### POIS
GET http://localhost:8000/api/pois
###
GET http://localhost:8000/api/pois/28929

### EVENTS
GET http://localhost:8000/api/events
###
GET http://localhost:8000/api/events/29218

### FAQS
GET http://localhost:8000/api/faqs
###
GET http://localhost:8000/api/faqs/29161

### TRANSPORTS
GET http://localhost:8000/api/transports
###
GET http://localhost:8000/api/transports/29149

### MESSAGES
GET http://localhost:8000/api/messages
###
GET http://localhost:8000/api/messages/28844

### PARTNERS
GET http://localhost:8000/api/partners
###
GET http://localhost:8000/api/partners/29276
  
### NEWSLETTERS
GET http://localhost:8000/api/newsletters
###
GET http://localhost:8000/api/newsletters/2948
###
POST http://localhost:8000/api/newsletters
content-type: application/json

{  
  "email":"henri.talfumier1@gmail.com"
}

### IMAGES
GET http://localhost:8000/api/images
###
GET http://localhost:8000/api/images/66894a324abffc91307c5418
###
POST http://localhost:8000/api/images
content-type: application/json

{  
  "images":[{
    "name": "vvv",
    "main": false,
    "lastModified":1235,
    "type":".jpg",
    "size": 345,
    "data":"tttttttt"
  }]
}
###
PUT http://localhost:8000/api/images/668bc6cf694186c931cad515
content-type: application/json

{  
  "images":[{
    "name": "vvvuuuuu",
    "main": false,
    "lastModified":1235,
    "type":".jpg",
    "size": 345,
    "data":"tttttttt"
  },{
    "name": "uuuuvvvvv",
    "main": false,
    "lastModified":1235,
    "type":".jpg",
    "size": 345,
    "data":"uuuuuuuu"
  }]
}
###
DELETE http://localhost:8000/api/images/668806c21ffb0e5cad3eb37f
###
DELETE http://localhost:8000/api/images/artist/28891/0

### TRANSLATE
POST http://localhost:8000/api/translate
content-type: application/json

{  
  "text":"invalid path",
  "to":"fr"
}

### USERS
POST http://localhost:8000/api/register
content-type: application/json

{  
  "last_name":"MARTINEZ2",  
  "first_name":"Henri",
  "email":"henri.talfumier2@wanadoo.fr",
  "role":"editor",
  "pwd":"1234H67£"
}
###
POST http://localhost:8000/api/login
content-type: application/json

{ 
  "email":"henri.talfumier@wanadoo.fr",
  "pwd":"1234H67£"
}
###
POST http://localhost:8000/api/login
content-type: application/json

{ 
  "email":"henri.talfumier1@wanadoo.fr",
  "pwd":"1234H67£"
}
###
PATCH http://localhost:8000/api/validate/3
x-auth-token:{{admin_token}}
content-type: application/json
###
PATCH http://localhost:8000/api/profile
x-auth-token:{{user_token}}
content-type: application/json

{
 "email":"henri12@xx.com"
}
###
GET http://localhost:8000/api/users
x-auth-token:{{admin_token}}
###
DELETE http://localhost:8000/api/users/4
x-auth-token:{{admin_token}}

