@admin_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibGFzdF9uYW1lIjoiTUFSVElORVoiLCJmaXJzdF9uYW1lIjoiSGVucmkiLCJlbWFpbCI6ImhlbnJpLnRhbGZ1bWllckB3YW5hZG9vLmZyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzE3NjA4NDkwLCJleHAiOjE3MTc2NjI0OTB9.eazpDjUG8tny4_8gpJM2kIvnmmC1ti_nBav1T1JwdAc
@user_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibGFzdF9uYW1lIjoiTUFSVElORVoiLCJmaXJzdF9uYW1lIjoiSGVucmkiLCJlbWFpbCI6ImhlbnJpLnRhbGZ1bWllcjFAd2FuYWRvby5mciIsInJvbGUiOiJlZGl0b3IiLCJpYXQiOjE3MTc2MTA2NDIsImV4cCI6MTcxNzY2NDY0Mn0.kdckHjKrAtBDIi57fMk_N9GcrUkI2qayrYLMdtPP1nk

### USERS
POST http://localhost:8000/api/register
content-type: application/json

{  
  "last_name":"MARTINEZ2",  
  "first_name":"Henri",
  "email":"henri.talfumier2@wanadoo.fr",
  "role":"editor",
  "pwd":"1234H67£"
}
###
POST http://localhost:8000/api/login
content-type: application/json

{ 
  "email":"henri.talfumier@wanadoo.fr",
  "pwd":"1234H67£"
}
###
POST http://localhost:8000/api/login
content-type: application/json

{ 
  "email":"henri.talfumier1@wanadoo.fr",
  "pwd":"1234H67£"
}
###
PATCH http://localhost:8000/api/validate/3
x-auth-token:{{admin_token}}
content-type: application/json
###
PATCH http://localhost:8000/api/profile
x-auth-token:{{user_token}}
content-type: application/json

{
 "email":"henri12@xx.com"
}
###
GET http://localhost:8000/api/users
x-auth-token:{{admin_token}}
###
DELETE http://localhost:8000/api/users/4
x-auth-token:{{admin_token}}

