name: Render Production Deployment

on:
  push:
    branches:
      - prod
jobs:
  main:
    name: Deploy to Render
    runs-on: ubuntu2004-x86_64
    steps:
      - name: Downlaod mongodb-tools
        run: wget https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2004-x86_64-100.10.0.tgz
      - name: Setup mongodb-tools
        run: sudo apt install ./mongodb-database-tools-*-100.10.0.tgz
      - name: Trigger deployment
        uses: sws2apps/render-deployment@main #consider using pin for dependabot auto update
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          multipleDeployment: false #optional, default true
